services:
    decorator_service:
        class: Amu\Bundle\DecoratorBundle\Service\Decorator
        autowire: true
        autoconfigure: true
        public: true
        arguments:
            - '@service_container'
            - '@logger'
            - '@twig'
        tags:
            - { name: monolog.logger, handler: amu  }

    twig.json:
        class: Amu\Bundle\DecoratorBundle\Twig\JsonExtension
        autowire: true
        autoconfigure: true
        public: true
        arguments:
            - '@service_container'
        tags:
            - { name: "twig.extension" }

    twig.custom_runtime:
        class: Amu\Bundle\DecoratorBundle\Twig\MyCustomTwigExtRuntime
        autowire: true
        autoconfigure: true
        public: true
        arguments:
            - '@service_container'
        tags:
            - { name: "twig.runtime" }

    # BEGIN new Maker tools service définition...
    maker.maker.make_translate:
        class: Amu\Bundle\DecoratorBundle\Maker\MakeTranslate
        arguments:
            - '@maker.file_manager'
            - '@maker.doctrine_helper'
            - '@maker.generator'
            - '@service_container'
        tags: [ "maker.command" ]

    maker.maker.make_decoration:
        class: Amu\Bundle\DecoratorBundle\Maker\MakeDecoration
        arguments:
            - '@maker.file_manager'
            - '@maker.doctrine_helper'
            - '@maker.generator'
            - '@service_container'
        tags: [ "maker.command" ]
    # END Maker tools service définition...

#    decorator.ajax_controller:
#        autowire: true
#        autoconfigure: true
#        public: true
#        class: Amu\Bundle\DecoratorBundle\Controller\ToolsController
#        arguments:
#            - $ws: '@decorator.ws_service'
